### ISSUE TITLE
Not helpful

### ISSUE THREAD

**Issue by buhrmi** [notwaldorf/ruby-eh#1]
This is not helpful at all.

**Comment by BlakeTurner** [comment]
I disagree. As a Canadian, I feel a new kinship with the Ruby Language. Thanks, eh?

**Comment by keithwhor** [comment]
take off hoser

**Comment by BlakeTurner** [comment]
Sorry.

**Comment by notwaldorf** [comment]
Also sorry. It is what it is. :)
